config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  resources :flagnotifications
  resources :notifications
  resources :amount_orders
  resources :invites
  resources :orders
  resources :friends
  resources :groups
  devise_for :users
  resources :counter

  

   root 'user#index'

   

  resources :groups do 
    resources :friends
  end

  

end

app/models/amount_order.rb
class AmountOrder < ActiveRecord::Base
  belongs_to :order
  belongs_to :user
end

app/controllers/amount_orders_controller.rb
class AmountOrdersController < ApplicationController
  before_action :set_amount_order, only: [:show, :edit, :update, :destroy]

  # GET /amount_orders
  # GET /amount_orders.json
  def index
    @amount_orders = AmountOrder.all
  end

  # GET /amount_orders/1
  # GET /amount_orders/1.json
  def show
  end

  # GET /amount_orders/new
  def new
    @amount_order = AmountOrder.new
  end

  # GET /amount_orders/1/edit
  def edit
  end

  # POST /amount_orders
  # POST /amount_orders.json
  def create
    @amount_order = AmountOrder.new(amount_order_params)

    respond_to do |format|
      if @amount_order.save
        format.html { redirect_to @amount_order, notice: 'Amount order was successfully created.' }
        format.json { render :show, status: :created, location: @amount_order }
      else
        format.html { render :new }
        format.json { render json: @amount_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /amount_orders/1
  # PATCH/PUT /amount_orders/1.json
  def update
    respond_to do |format|
      if @amount_order.update(amount_order_params)
        format.html { redirect_to @amount_order, notice: 'Amount order was successfully updated.' }
        format.json { render :show, status: :ok, location: @amount_order }
      else
        format.html { render :edit }
        format.json { render json: @amount_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /amount_orders/1
  # DELETE /amount_orders/1.json
  def destroy
    @amount_order.destroy
    respond_to do |format|
      format.html { redirect_to amount_orders_url, notice: 'Amount order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_amount_order
      @amount_order = AmountOrder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def amount_order_params
      params.require(:amount_order).permit(:item, :comment, :amount, :price, :order_id, :user_id)
    end
end

app/helpers/amount_orders_helper.rb
module AmountOrdersHelper
end

app/views/amount_orders/_form.html.erb
<%= form_for(@amount_order) do |f| %>
  <% if @amount_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@amount_order.errors.count, "error") %> prohibited this amount_order from being saved:</h2>

      <ul>
      <% @amount_order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item %><br>
    <%= f.text_area :item %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :order_id %><br>
    <%= f.text_field :order_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/amount_orders/edit.html.erb
<h1>Editing Amount Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @amount_order %> |
<%= link_to 'Back', amount_orders_path %>

app/views/amount_orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Amount Orders</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Comment</th>
      <th>Amount</th>
      <th>Price</th>
      <th>Order</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @amount_orders.each do |amount_order| %>
      <tr>
        <td><%= amount_order.item %></td>
        <td><%= amount_order.comment %></td>
        <td><%= amount_order.amount %></td>
        <td><%= amount_order.price %></td>
        <td><%= amount_order.order %></td>
        <td><%= amount_order.user %></td>
        <td><%= link_to 'Show', amount_order %></td>
        <td><%= link_to 'Edit', edit_amount_order_path(amount_order) %></td>
        <td><%= link_to 'Destroy', amount_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Amount order', new_amount_order_path %>

app/views/amount_orders/new.html.erb
<h1>New Amount Order</h1>

<%= render 'form' %>

<%= link_to 'Back', amount_orders_path %>

app/views/amount_orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @amount_order.item %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @amount_order.comment %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @amount_order.amount %>
</p>

<p>
  <strong>Price:</strong>
  <%= @amount_order.price %>
</p>

<p>
  <strong>Order:</strong>
  <%= @amount_order.order %>
</p>

<p>
  <strong>User:</strong>
  <%= @amount_order.user %>
</p>

<%= link_to 'Edit', edit_amount_order_path(@amount_order) %> |
<%= link_to 'Back', amount_orders_path %>